services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=M1stAut0maxion
      - DOCKER_INFLUXDB_INIT_PASSWORD=shynasammuna
      - DOCKER_INFLUXDB_INIT_ORG=Capstone
      - DOCKER_INFLUXDB_INIT_BUCKET=Mist_info
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=9e37c51b-6ffe-4e78-8382-007caf2d1077
      - DOCKER_INFLUXDB_INIT_PORT=8086
      - DOCKER_INFLUXDB_INIT_HOST=influxdb
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    restart: always

  pythonapp:
    build: .
    container_name: mistapimonitoring
    depends_on:
      - influxdb
    network_mode: host
    restart: always
    
networks:
  host:
    driver: bridge
    external: true
  monitoring:
    driver: bridge
    external: true

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true